#!/usr/bin/env bash
# Requirements:
#install nginx on your webserver, configure nginx to run on port 80.

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
