#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Create a custom Nginx configuration file
sudo cat << EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By $HOSTNAME;
    }
}
EOF

# Enable the Nginx configuration
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
